import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'
import LanguageDetector from 'i18next-browser-languagedetector'

const resources = {
  en: {
    translation: {
      nav_home: 'Home', nav_about: 'About', nav_profile: 'Profile', nav_skills: 'Skills', nav_projects: 'Projects', nav_experience: 'Experience', nav_education: 'Education', nav_languages: 'Languages', nav_interests: 'Interests', nav_contact: 'Contact', language_switch_english_short: 'EN', language_switch_french_short: 'FR',
      person_name: 'ANDRIATAHIANA Sandratra Josiah', person_initials: 'ASJ', brand_mark: 'Me', brand_name: 'Sandratra', profile_birthday: '22 July 2002',
      hero_available: 'Available for work', hero_download: 'Download CV', hero_contact: 'Get in touch', hero_scroll: 'Scroll', hero_github: 'GitHub', hero_scroll_aria: 'Scroll to the about section',
      hero_role_student: 'Software Engineering Student', hero_role_developer: 'Full Stack Developer', hero_intro: 'I enjoy building modern web applications, desktop software and database-driven systems. My long-term dream is to create useful software and even video games that can impact people’s lives.', hero_location: 'Faratsiho, Madagascar', hero_degree: 'Bachelor in Software Engineering',
      stat_years_coding: 'Years of coding', stat_languages_mastered: 'Languages mastered', stat_projects_shipped: 'Projects shipped', stat_months_available: 'Months available',
      about_label: 'About me', about_title: 'A student building software on purpose', about_description: 'Where I come from, what I study, and where I am heading next.', about_story_one: 'Before joining Université Adventiste Zurcher, I spent one year studying Computer Science at CNTEMAD. That year gave me my first real contact with programming and confirmed the field I wanted to build my career in.', about_story_two: 'Because of that year, my Bachelor in Software Engineering ends in 2027 instead of 2026. I do not see it as lost time: it is the year that made me choose software engineering on purpose, and not by accident.',
      about_fact_full_name: 'Full name', about_fact_birthday: 'Birthday', about_fact_current_city: 'Current city', about_fact_looking_for_internship: 'Looking for an internship', about_fact_internship_duration: 'Internship duration', about_fact_university: 'University', about_fact_degree: 'Degree', about_fact_study_period: 'Study period', about_fact_previous_study: 'Previous study',
      profile_city: 'Faratsiho, Vakinankaratra, Madagascar', profile_internship_city: 'Antananarivo', profile_internship_duration: '3 months', profile_university: 'Université Adventiste Zurcher', profile_degree: 'Bachelor in Software Engineering', profile_study_period: '2021–2027', profile_previous_study: 'CNTEMAD (Computer Science)',
      profile_label: 'Professional profile', profile_title: 'Why I build software', profile_description: 'From a curiosity about video games to a serious engineering practice.', profile_story_one: 'I became passionate about software engineering through video games. Trying to understand how they were built pushed me to learn how software works, and I never stopped since.', profile_story_two: 'Today I work mainly on web development, databases and desktop applications. I like designing data models as much as I like building the interfaces that consume them.', profile_story_three: 'My goal is to create useful software — tools people actually keep using — and one day video games that people enjoy playing. I am looking for an internship where I can work on real projects and improve my engineering skills next to experienced developers.', profile_web: 'Web development', profile_web_text: 'React front ends and PHP back ends.', profile_databases: 'Databases', profile_databases_text: 'Relational modelling, SQL and NoSQL stores.', profile_desktop: 'Desktop apps', profile_desktop_text: 'Java and C# applications for real users.', profile_goal: 'Long-term goal', profile_goal_text: 'Useful software, and one day video games.',
      skills_label: 'Skills', skills_title: 'Tools I use every day', skills_description: 'Languages, databases, systems and tools I am comfortable with, and the ones I still have to learn.', skills_languages: 'Programming languages', skills_databases: 'Databases', skills_os: 'Operating systems', skills_tools: 'Development tools', skills_learning: 'Still to learn', skills_favorite: 'Favourite', skill_level_advanced: 'Advanced', skill_level_intermediate: 'Intermediate',
      projects_label: 'Projects', projects_title: 'Things I have built', projects_description: 'Mobile, web and personal projects where I learned the most.', projects_placeholder: 'Image placeholder', projects_demo_soon: 'Live demo coming soon', projects_status_done: 'Completed', projects_status_progress: 'In progress', projects_view_demo: 'View demo', projects_view_code: 'View code', projects_screenshot_alt: '{{title}} screenshot', projects_code_aria: 'View {{title}} source code on GitHub', projects_demo_aria: 'View {{title}} live demo', projects_demo_soon_aria: 'Live demo coming soon',
      project_bloom_title: 'Bloom', project_crypto_title: 'CryptoPlatform', project_personal_title: 'Personal Software Project', project_bloom_tagline: 'Android application for plant recognition', project_bloom_description: 'Bloom identifies plants from a photo and keeps a personal collection of every plant the user has scanned.', project_bloom_feature_one: 'Plant identification', project_bloom_feature_two: 'Firebase authentication', project_bloom_feature_three: 'Room database', project_bloom_feature_four: 'Claude AI API', project_crypto_tagline: 'Crypto trading simulator', project_crypto_description: 'An educational trading simulator built with React. It uses real Binance market data so users can practise trading without risking real money.', project_crypto_feature_one: 'Real Binance market data', project_crypto_feature_two: 'Simulated portfolio', project_crypto_feature_three: 'Educational project', project_personal_tagline: 'Currently under development', project_personal_description: 'A personal software project focused on improving my software engineering skills, from architecture and data modelling to delivery.', project_personal_feature_one: 'Clean architecture', project_personal_feature_two: 'Database-driven', project_personal_feature_three: 'Work in progress', project_personal_tech: 'To be announced',
      experience_label: 'Experience', experience_title: 'What I have practised so far', experience_description: 'Development work and hands-on computer maintenance since 2023.', experience_since_2023: 'Since 2023', experience_development_role: 'Software application development', experience_development_one: 'Web applications with PHP, JavaScript and React', experience_development_two: 'Desktop applications with Java and C#', experience_development_three: 'Relational and NoSQL database design', experience_maintenance_role: 'Computer maintenance', experience_maintenance_one: 'Windows installation', experience_maintenance_two: 'Linux installation', experience_maintenance_three: 'Hardware diagnostics', experience_maintenance_four: 'Computer repair', experience_maintenance_five: 'Development environment setup',
      education_label: 'Education', education_title: 'My academic path', education_description: 'One year of Computer Science, then a full Software Engineering degree.', education_zurcher_degree: 'Bachelor in Software Engineering', education_cntemad_degree: 'Computer Science',
      languages_label: 'Languages', languages_title: 'How I communicate', languages_description: 'Malagasy at home, French at university, English for documentation and code.', language_malagasy: 'Malagasy', language_french: 'French', language_english: 'English', language_level_native: 'Native', language_level_good: 'Good', language_level_intermediate: 'Intermediate',
      qualities_label: 'Qualities', qualities_title: 'My strengths', qualities_description: 'The traits that help me succeed as a developer.', qualities_note: 'I am most productive when I work independently and own a problem from end to end. I also keep working on my teamwork skills, because the software I want to build is never written alone.', quality_curious: 'Curious', quality_autonomous: 'Autonomous', quality_problem_solver: 'Problem solver', quality_analytical_thinking: 'Analytical thinking', quality_serious: 'Serious', quality_fast_learner: 'Able to learn quickly',
      interests_label: 'Interests', interests_title: 'What I enjoy', interests_description: 'Beyond coding, here are the things that keep me engaged.', interest_software: 'Software development', interest_games: 'Video games', interest_basketball: 'Basketball', interest_automobiles: 'Automobiles', driving_license: 'Driving licence', all_categories: 'All four categories',
      contact_label: 'Contact', contact_title: 'Let us build something together', contact_description: 'I am currently looking for a 3-month internship in Antananarivo.', contact_heading: 'Open to internship offers', contact_text: 'I am looking for a 3-month internship in {{city}}. Preferred positions:', contact_send: 'Send an email', contact_github: 'GitHub profile', contact_email: 'Email', contact_phone: 'Phone', contact_github_url: 'github.com/Lessa22', contact_position_web: 'Web developer', contact_position_software: 'Software developer', contact_position_any: 'Any Software Engineering opportunity',
      aria_switch_english: 'Switch to English', aria_switch_french: 'Switch to French', aria_open_menu: 'Open menu', aria_close_menu: 'Close menu', aria_section_dock: 'Section dock', aria_download_cv: 'Download CV', aria_contact_me: 'Contact me', aria_github_profile: 'View GitHub profile', aria_send_email: 'Send email to me', aria_send_email_to: 'Send email to {{email}}', aria_call: 'Call {{phone}}', aria_back_to_top: 'Back to top',
      footer_rights: 'All rights reserved', footer_made_with: 'Made with React', app_loading: 'Loading section…',
    },
  },
  fr: {
    translation: {
      nav_home: 'Accueil', nav_about: 'À propos', nav_profile: 'Profil', nav_skills: 'Compétences', nav_projects: 'Projets', nav_experience: 'Expérience', nav_education: 'Éducation', nav_languages: 'Langues', nav_interests: 'Centres d’intérêt', nav_contact: 'Contact', language_switch_english_short: 'EN', language_switch_french_short: 'FR',
      person_name: 'ANDRIATAHIANA Sandratra Josiah', person_initials: 'ASJ', brand_mark: 'Me', brand_name: 'Sandratra', profile_birthday: '22 juillet 2002',
      hero_available: 'Disponible pour travailler', hero_download: 'Télécharger le CV', hero_contact: 'Me contacter', hero_scroll: 'Défiler', hero_github: 'GitHub', hero_scroll_aria: 'Défiler vers la section À propos',
      hero_role_student: 'Étudiant en génie logiciel', hero_role_developer: 'Développeur Full Stack', hero_intro: 'J’aime créer des applications web modernes, des logiciels de bureau et des systèmes pilotés par les données. Mon rêve à long terme est de créer des logiciels utiles et même des jeux vidéo qui peuvent avoir un impact sur la vie des gens.', hero_location: 'Faratsiho, Madagascar', hero_degree: 'Licence en génie logiciel',
      stat_years_coding: 'Années de programmation', stat_languages_mastered: 'Langages maîtrisés', stat_projects_shipped: 'Projets livrés', stat_months_available: 'Mois disponibles',
      about_label: 'À propos de moi', about_title: 'Un étudiant qui construit des logiciels par choix', about_description: 'D’où je viens, ce que j’étudie et où je vais ensuite.', about_story_one: 'Avant de rejoindre l’Université Adventiste Zurcher, j’ai passé une année à étudier l’informatique au CNTEMAD. Cette année m’a donné mon premier vrai contact avec la programmation et a confirmé le domaine dans lequel je voulais construire ma carrière.', about_story_two: 'À cause de cette année, ma licence en génie logiciel se termine en 2027 au lieu de 2026. Je ne la considère pas comme du temps perdu : c’est l’année qui m’a fait choisir le génie logiciel consciemment, et non par hasard.',
      about_fact_full_name: 'Nom complet', about_fact_birthday: 'Date de naissance', about_fact_current_city: 'Ville actuelle', about_fact_looking_for_internship: 'Recherche de stage', about_fact_internship_duration: 'Durée du stage', about_fact_university: 'Université', about_fact_degree: 'Diplôme', about_fact_study_period: 'Période d’études', about_fact_previous_study: 'Études précédentes',
      profile_city: 'Faratsiho, Vakinankaratra, Madagascar', profile_internship_city: 'Antananarivo', profile_internship_duration: '3 mois', profile_university: 'Université Adventiste Zurcher', profile_degree: 'Licence en génie logiciel', profile_study_period: '2021–2027', profile_previous_study: 'CNTEMAD (Informatique)',
      profile_label: 'Profil professionnel', profile_title: 'Pourquoi je construis des logiciels', profile_description: 'De la curiosité pour les jeux vidéo à une pratique sérieuse de l’ingénierie.', profile_story_one: 'Je me suis passionné pour le génie logiciel grâce aux jeux vidéo. Essayer de comprendre comment ils étaient construits m’a poussé à apprendre comment fonctionne un logiciel, et je ne me suis jamais arrêté depuis.', profile_story_two: 'Aujourd’hui, je travaille principalement sur le développement web, les bases de données et les applications de bureau. J’aime concevoir des modèles de données autant que créer les interfaces qui les utilisent.', profile_story_three: 'Mon objectif est de créer des logiciels utiles — des outils que les gens continuent réellement à utiliser — et un jour des jeux vidéo que les gens aiment jouer. Je recherche un stage où je pourrai travailler sur de vrais projets et améliorer mes compétences d’ingénieur aux côtés de développeurs expérimentés.', profile_web: 'Développement web', profile_web_text: 'Interfaces React et back-ends PHP.', profile_databases: 'Bases de données', profile_databases_text: 'Modélisation relationnelle, SQL et magasins NoSQL.', profile_desktop: 'Applications de bureau', profile_desktop_text: 'Applications Java et C# pour de vrais utilisateurs.', profile_goal: 'Objectif à long terme', profile_goal_text: 'Des logiciels utiles, et un jour des jeux vidéo.',
      skills_label: 'Compétences', skills_title: 'Les outils que j’utilise chaque jour', skills_description: 'Langages, bases de données, systèmes et outils avec lesquels je suis à l’aise, ainsi que ceux que je dois encore apprendre.', skills_languages: 'Langages de programmation', skills_databases: 'Bases de données', skills_os: 'Systèmes d’exploitation', skills_tools: 'Outils de développement', skills_learning: 'À apprendre', skills_favorite: 'Préféré', skill_level_advanced: 'Avancé', skill_level_intermediate: 'Intermédiaire',
      projects_label: 'Projets', projects_title: 'Ce que j’ai construit', projects_description: 'Projets mobiles, web et personnels où j’ai le plus appris.', projects_placeholder: 'Espace réservé pour l’image', projects_demo_soon: 'Démo en ligne bientôt disponible', projects_status_done: 'Terminé', projects_status_progress: 'En cours', projects_view_demo: 'Voir la démo', projects_view_code: 'Voir le code', projects_screenshot_alt: 'Capture d’écran de {{title}}', projects_code_aria: 'Voir le code source de {{title}} sur GitHub', projects_demo_aria: 'Voir la démo en ligne de {{title}}', projects_demo_soon_aria: 'Démo en ligne bientôt disponible',
      project_bloom_title: 'Bloom', project_crypto_title: 'CryptoPlatform', project_personal_title: 'Projet logiciel personnel', project_bloom_tagline: 'Application Android de reconnaissance des plantes', project_bloom_description: 'Bloom identifie les plantes à partir d’une photo et conserve une collection personnelle de chaque plante numérisée.', project_bloom_feature_one: 'Identification des plantes', project_bloom_feature_two: 'Authentification Firebase', project_bloom_feature_three: 'Base de données Room', project_bloom_feature_four: 'API Claude AI', project_crypto_tagline: 'Simulateur de trading crypto', project_crypto_description: 'Un simulateur de trading éducatif créé avec React. Il utilise de vraies données de marché Binance pour permettre aux utilisateurs de s’exercer sans risquer de l’argent réel.', project_crypto_feature_one: 'Données de marché Binance en temps réel', project_crypto_feature_two: 'Portefeuille simulé', project_crypto_feature_three: 'Projet éducatif', project_personal_tagline: 'Actuellement en développement', project_personal_description: 'Un projet logiciel personnel axé sur l’amélioration de mes compétences en génie logiciel, de l’architecture et la modélisation des données jusqu’à la livraison.', project_personal_feature_one: 'Architecture propre', project_personal_feature_two: 'Piloté par les données', project_personal_feature_three: 'Travail en cours', project_personal_tech: 'À annoncer',
      experience_label: 'Expérience', experience_title: 'Ce que j’ai pratiqué jusqu’ici', experience_description: 'Travail de développement et maintenance informatique pratique depuis 2023.', experience_since_2023: 'Depuis 2023', experience_development_role: 'Développement d’applications logicielles', experience_development_one: 'Applications web avec PHP, JavaScript et React', experience_development_two: 'Applications de bureau avec Java et C#', experience_development_three: 'Conception de bases de données relationnelles et NoSQL', experience_maintenance_role: 'Maintenance informatique', experience_maintenance_one: 'Installation de Windows', experience_maintenance_two: 'Installation de Linux', experience_maintenance_three: 'Diagnostic matériel', experience_maintenance_four: 'Réparation d’ordinateurs', experience_maintenance_five: 'Configuration d’environnements de développement',
      education_label: 'Éducation', education_title: 'Mon parcours académique', education_description: 'Une année d’informatique, puis une licence complète en génie logiciel.', education_zurcher_degree: 'Licence en génie logiciel', education_cntemad_degree: 'Informatique',
      languages_label: 'Langues', languages_title: 'Comment je communique', languages_description: 'Malagasy à la maison, français à l’université, anglais pour la documentation et le code.', language_malagasy: 'Malagasy', language_french: 'Français', language_english: 'Anglais', language_level_native: 'Langue maternelle', language_level_good: 'Bon niveau', language_level_intermediate: 'Intermédiaire',
      qualities_label: 'Qualités', qualities_title: 'Mes forces', qualities_description: 'Les traits qui m’aident à réussir comme développeur.', qualities_note: 'Je suis plus productif lorsque je travaille de manière indépendante et que je prends en charge un problème de bout en bout. Je continue également à développer mes compétences de travail en équipe, car le logiciel que je veux créer ne s’écrit jamais seul.', quality_curious: 'Curieux', quality_autonomous: 'Autonome', quality_problem_solver: 'Résolution de problèmes', quality_analytical_thinking: 'Esprit analytique', quality_serious: 'Sérieux', quality_fast_learner: 'Apprend rapidement',
      interests_label: 'Centres d’intérêt', interests_title: 'Ce que j’aime', interests_description: 'Au-delà du code, voici ce qui me passionne.', interest_software: 'Développement logiciel', interest_games: 'Jeux vidéo', interest_basketball: 'Basket-ball', interest_automobiles: 'Automobiles', driving_license: 'Permis de conduire', all_categories: 'Les quatre catégories',
      contact_label: 'Contact', contact_title: 'Construisons quelque chose ensemble', contact_description: 'Je recherche actuellement un stage de 3 mois à Antananarivo.', contact_heading: 'Ouvert aux offres de stage', contact_text: 'Je recherche un stage de 3 mois à {{city}}. Postes préférés :', contact_send: 'Envoyer un e-mail', contact_github: 'Profil GitHub', contact_email: 'E-mail', contact_phone: 'Téléphone', contact_github_url: 'github.com/Lessa22', contact_position_web: 'Développeur web', contact_position_software: 'Développeur logiciel', contact_position_any: 'Toute opportunité en génie logiciel',
      aria_switch_english: 'Passer à l’anglais', aria_switch_french: 'Passer au français', aria_open_menu: 'Ouvrir le menu', aria_close_menu: 'Fermer le menu', aria_section_dock: 'Navigation des sections', aria_download_cv: 'Télécharger le CV', aria_contact_me: 'Me contacter', aria_github_profile: 'Voir le profil GitHub', aria_send_email: 'M’envoyer un e-mail', aria_send_email_to: 'Envoyer un e-mail à {{email}}', aria_call: 'Appeler {{phone}}', aria_back_to_top: 'Retour en haut',
      footer_rights: 'Tous droits réservés', footer_made_with: 'Créé avec React', app_loading: 'Chargement de la section…',
    },
  },
}

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    initImmediate: false,
    fallbackLng: 'en',
    supportedLngs: ['en', 'fr'],
    interpolation: { escapeValue: false },
    detection: {
      order: ['localStorage', 'navigator'],
      lookupLocalStorage: 'portfolio-language',
      caches: ['localStorage'],
    },
  })

i18n.on('languageChanged', (language) => {
  if (typeof document !== 'undefined') document.documentElement.lang = language
})

export default i18n
